# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = true

  config.vm.network "private_network", ip: "192.168.70.10"
  config.vm.synced_folder "~", "/host"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Triage"
    vb.gui = false
    vb.cpus = 2
    vb.memory = "4096"
  end

  config.vm.provision "shell", path: "config/setup.sh", privileged: false
  config.vm.provision "shell", path: "config/envvars.sh", run: "always"
end
